### ISSUE TITLE
Get neural2d working in Microsoft Visual Studio

### ISSUE THREAD

**Issue by davidrmiller** [davidrmiller/neural2d#10]
Bob Zigon suggests: Get neural2d working in Microsoft Visual Studio.

The biggest hurdle is the bit of networking used to support the webserver GUI interface. Apparently Microsoft does not support the POSIX standard very well for networking, and a few things would have to be recoded in Microsoft-specific terms.

**Comment by jeandudey** [comment]
Why you dont use a build system like CMake to generate Visual Studio projects.
