### ISSUE TITLE
Visual Studio 2013 or above version is required to compile the neural2d-master source code

### ISSUE THREAD

**Issue by ZhaowuLuo** [davidrmiller/neural2d#24]
Due to lack of the support  for the required C++ 11 features on the part of the C++ compilers of Microsoft Visual Studio 2012 or prior versions on the Windows platform,  the neural2d-master source code of the neural2d  project must be generated in CMake specifying Visual Studio 2013 or above versions. Otherwise, many compiling errors are expected inside the  Visual Studio.

**Comment by davidrmiller** [comment]
Thank you very much for reporting this. I've updated the minimum requirements in the README.md file, changed the example of how to use cmake -G, and updated the relevant wiki page.

I'll close this issue for now as resolved, but feel free to reopen it to add any discussion or documentation relating to this matter.
