### ISSUE TITLE
How do I input custom 2D values?

### ISSUE THREAD

**Issue by MaDooSan** [davidrmiller/neural2d#29]
I'm currently using numerical inputs as training data, but I can only input 1-dimensional values in the following format:
{x x x x x} y y 
as explained in the documentation.

Is there a way to directly enter 2D data as well? Just wondering!

Thanks :)

**Comment by davidrmiller** [comment]
(This applies when entering training data as text inside inputData.txt.) Just arrange your 2D input values in one long linear list. For example, if your net has 16x16 inputs, you'll have 256 numbers inside the { } curly braces.

**Comment by MaDooSan** [comment]
That's wonderful. Thanks David!
