### ISSUE TITLE
The webserver socket takes a while to timeout after neural2d exits.

### ISSUE THREAD

**Issue by davidrmiller** [davidrmiller/neural2d#3]
After using the web interface, the network socket doesn't seem to be getting closed cleanly. It sometimes takes on the order of a minute after neural2d exits before it can be run again.

**Comment by mwhidden** [comment]
You've encountered TCP's TIME_WAIT feature. To bypass add these includes to webserver.cpp:

    #include <sys/types.h>
    #include <sys/socket.h>


And, before the 'bind' in webserver.cpp, add this code so set SO_REUSEADDR:


    // set SO_REUSEADDR so we can bind the port even if there are
    // connections it TIME_WAIT, thus allowing the webserver to be
    // restarted without waiting for the TIME_WAIT to expire.
    setsockopt(socketFd, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval));

**Comment by mwhidden** [comment]
Whoops! Forgot to declare optval and set the value to 1 in that code snippet. I edited the comment.

**Comment by davidrmiller** [comment]
Brilliant! Tested successfully on Cygwin/Windows and Linux.

From what I can tell, <sys/types.h> is not strictly required for modern Cygwin and Linux, but may be required by some older systems, so it's good to include it.

Thanks for this fix.

**Comment by mwhidden** [comment]
I found it to be needed for the latest Ubuntu Linux.
