### ISSUE TITLE
Question about colors

### ISSUE THREAD

**Issue by MaDooSan** [davidrmiller/neural2d#31]
This is not so much an 'issue' as a question about how this neural net works, and forgive my ignorance if this was mentioned in your documentation. Since this is a 2D NN, if I were to imagine the input layer as one dimension being input pixels along the x axis and the other being input pixels along the y axis, how is the color information managed? Do you assign a specific range (between, say, -1 to 1) to a single channel? 

Thanks in advance!

Madhu

**Comment by davidrmiller** [comment]
Hi @MaDooSan,  Currently, by default, each color pixel in the BMP image gets converted to a floating point monochrome value in the range -1.0..+1.0, and that's what gets copied to the input neurons.

Alternatively, you can input just a single color channel from the BMP image with the [color channel parameter](https://github.com/davidrmiller/neural2d/wiki/ParameterList#color-channel-training-validate-trained-modes).

The default conversion to monochrome is (0.3Red + 0.6Green + 0.1Blue), a common photographic conversion. To modify that, see ImageReaderBMP::getData().

Currently, neural2d cares only that the number of pixels in each BMP file is equal to the number of neurons in the input layer. The program does not care if the dimensionality is the same. For example, if your input layer has 64 neurons arranged in any width and height, then each BMP file must also have exactly 64 pixels, and they can be arranged in any width and height, even different. (If the dimensionality is different, we assume you know what you're doing with your input data.) The pixel values get assigned to the input neurons, one pixel per neuron, reading the source pixels across the columns and down the rows (relative to the image file) and writing the values to the input layer across the columns and down the rows (relative to the neural net input layer).

**Comment by MaDooSan** [comment]
Ahh, I see. That makes a lot of sense. Thanks for clarifying the conversion factor, I must have missed that.

Cheers!
