### ISSUE TITLE
Can't compile under windows using MSYS2/MSYS

### ISSUE THREAD

**Issue by jeandudey** [davidrmiller/neural2d#9]
When i use MSYS2/MSYS to compile neural2d i got the following error:

```
neural2d.h:105:46: fatal error: sys/socket.h: No such file or directory
```

**Comment by davidrmiller** [comment]
Thanks for the report. Currently, neural2d is supported on Windows using Cygwin. I don't know what it would take to get it running in an MSYS2/MSYS environment, but you might get some clues from http://stackoverflow.com/questions/1517762/sockets-in-mingw . If you succeed in getting it to work under MSYS2/MSYS, feel free to submit a patch or post notes here. Thanks.

**Comment by jeandudey** [comment]
Another solution is that we create another makefile like "Makefile.mingw" with the flag -DDISABLE_WEBSERVER & without compiling webserver.c
